/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import { useEffect, useState } from "react";
import MainPage from "./Components/MainPage";
import Header from "./Components/ui/Header";
import Navbar from "./Components/ui/Navbar";
import { MainContext } from "./Context";
import Categories from "./Components/Categories";
export default function Home() {
  const [recipeVal, setRecipeVal] = useState([]);
  const [profile, setProfile] = useState([]);
  const [screen, setScreen] = useState(<Categories />);
  const data = {
    recipeVal, setRecipeVal, screen, setScreen, profile, setProfile,
  };
  return (
    <MainContext.Provider value={data}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="w-full h-screen bg-BackgroundColor flex items-center justify-center">
        <div className="w-96 h-4/5 bg-ThirdBrandColor rounded-3xl drop-shadow-2xl shadow-2xl flex items-center justify-start py-5 flex-col pb-[80px]  ">
          <Header />
          <MainPage />
          <Navbar />
        </div>
      </main>
    </MainContext.Provider>
  );
}
